# SPDX-FileCopyrightText: 2025 Sergio Martins
# SPDX-License-Identifier: MIT

name: Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_to_testflight:
        type: boolean
        required: true
        description: "Whether this is a release build to be sent to TestFlight"

jobs:
  build:
    name: Build (${{ matrix.preset }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        preset: [ios-dev]
        os: [macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt for macOS
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.0'
        cache: true

    - name: Print Qt environment
      run: echo "QT_ROOT_DIR=$QT_ROOT_DIR"

    - name: Install Qt for iOS
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.0'
        cache: true
        target: ios

    - name: Print Qt environment2
      run: echo "QT_ROOT_DIR=$QT_ROOT_DIR"

    - name: Setup vcpkg
      run: |
        cd 3rdparty/vcpkg
        ./bootstrap-vcpkg.sh

    - name: debug
      run: |
        which qmake
        which qt-cmake

    - name: Configure CMake
      env:
        POINTLESS_SUPABASE_URL: ${{ secrets.POINTLESS_SUPABASE_URL }}
        POINTLESS_SUPABASE_ANON_KEY: ${{ secrets.POINTLESS_SUPABASE_ANON_KEY }}
        QT_INSTALL: ${{ env.QT_ROOT_DIR }}
      run: qt-cmake --preset=${{ matrix.preset }}

    - name: Build
      run: cmake --build build-${{ matrix.preset }}
