# SPDX-FileCopyrightText: 2025 Sergio Martins
# SPDX-License-Identifier: MIT

name: Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.preset }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        preset: [ios-debug]
        os: [macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt for macOS
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.0'
        cache: true

    - name: Install Qt for iOS
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.0'
        cache: true
        target: ios

    - name: Setup vcpkg
      run: |
        cd 3rdparty/vcpkg
        ./bootstrap-vcpkg.sh

    # - name: Configure CMake
    #   env:
    #     POINTLESS_SUPABASE_URL: ${{ secrets.POINTLESS_SUPABASE_URL }}
    #     POINTLESS_SUPABASE_ANON_KEY: ${{ secrets.POINTLESS_SUPABASE_ANON_KEY }}
    #   run: cmake --preset=${{ matrix.preset }}

    # - name: Build
    #   run: cmake --build build-${{ matrix.preset }}
