# SPDX-FileCopyrightText: 2025 Sergio Martins
# SPDX-License-Identifier: MIT

name: Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_to_testflight:
        type: boolean
        required: true
        description: "Whether this is a release build to be sent to TestFlight"

jobs:
  build:
    name: Build (${{ matrix.preset }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        preset: [ios-release]
        os: [macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup signing
      run: |
        ./scripts/ci-dump-base64-to-file.sh
        ./scripts/ci-setup-ios-keychain.sh
      env:
        APPLE_PROVISIONING_PROFILE_BASE64: ${{ secrets.APPLE_PROVISIONING_PROFILE_BASE64 }}
        APPLE_CERTIFICATE_P12_BASE64: ${{ secrets.APPLE_CERTIFICATE_P12_BASE64 }}
        APPLE_CERTIFICATE_P12_PATH: ${{ runner.temp }}/cert.p12
        APPLE_PROVISIONING_PROFILE_PATH: ${{ runner.temp }}/profile.mobileprovision
        KEYCHAIN_FILE: ${{ runner.temp }}/ios-build.keychain
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        APPLE_P12_PASSWORD: ${{ secrets.APPLE_P12_PASSWORD }}

    - name: Install Qt for macOS
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.0'
        cache: true

    - name: Install Qt for iOS
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.0'
        cache: true
        target: ios

    - name: Setup vcpkg
      run: |
        cd 3rdparty/vcpkg
        ./bootstrap-vcpkg.sh

    - name: Configure CMake
      env:
        POINTLESS_SUPABASE_URL: ${{ secrets.POINTLESS_SUPABASE_URL }}
        POINTLESS_SUPABASE_ANON_KEY: ${{ secrets.POINTLESS_SUPABASE_ANON_KEY }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        QT_INSTALL: ${{ env.QT_ROOT_DIR }}
        APPLE_PROVISIONING_PROFILE_UUID: ${{ secrets.APPLE_PROVISIONING_PROFILE_UUID }}
      run: cmake --preset=${{ matrix.preset }}

    - name: Build
      env:
        POINTLESS_SUPABASE_URL: ${{ secrets.POINTLESS_SUPABASE_URL }}
        POINTLESS_SUPABASE_ANON_KEY: ${{ secrets.POINTLESS_SUPABASE_ANON_KEY }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        QT_INSTALL: ${{ env.QT_ROOT_DIR }}
      run: cmake --build build-${{ matrix.preset }}
