# SPDX-FileCopyrightText: 2025 Sergio Martins
# SPDX-License-Identifier: MIT

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.preset }} ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        preset: [dev, rel, dev-asan, dev-tsan]
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install clang
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-20
        sudo apt-get remove --purge clang-18

    - name: Set clang-20 as default clang/clang++
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100

    - name: Print gcc/clang version
      if: matrix.os == 'ubuntu-latest'
      run: |
        g++ --version
        clang++ --version

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.0'
        cache: true

    - name: Setup vcpkg
      run: |
        cd 3rdparty/vcpkg
        ./bootstrap-vcpkg.sh

    - name: Configure CMake
      env:
        POINTLESS_SUPABASE_URL: ${{ secrets.POINTLESS_SUPABASE_URL }}
        POINTLESS_SUPABASE_ANON_KEY: ${{ secrets.POINTLESS_SUPABASE_ANON_KEY }}
      run: cmake --preset=${{ matrix.preset }}

    - name: Build
      run: cmake --build build-${{ matrix.preset }}

    - name: Run tests
      if: matrix.preset != 'dev-tsan'
      env:
        POINTLESS_SUPABASE_URL: ${{ secrets.POINTLESS_SUPABASE_URL }}
        POINTLESS_SUPABASE_ANON_KEY: ${{ secrets.POINTLESS_SUPABASE_ANON_KEY }}
        POINTLESS_DEBUG_USERNAME: ${{ secrets.POINTLESS_DEBUG_USERNAME }}
        POINTLESS_DEBUG_PASSWORD: ${{ secrets.POINTLESS_DEBUG_PASSWORD }}
        QT_QPA_PLATFORM: offscreen
      run: ctest --output-on-failure --verbose --test-dir build-${{ matrix.preset }}

    - name: Run qmllint
      run: |
        ninja -C ./build-${{ matrix.preset }} all_qmllint
